#baseUrl : https://prod-server.andaman7.com/public/v1/api-docs
baseUrl : http://localhost:8080/public/v1/api-docs
endpointsPath : /endpoints/
endpoints :
  - name : Users
    uri : /users
    page : users
    fa-icon : users
  - name : Authenticated user
    uri : /users/me
    page : users-me
    fa-icon : user
  - name : Devices
    uri : /users/me/devices
    page : devices
    fa-icon : tablet
  - name : Trusted users
    uri : /users/me/trusted-users
    page : trusted-users
    fa-icon : users
  - name : EHRs
    uri : /users/%7BuserId%7D/ehrs
    page : ehrs
    fa-icon : medkit
  - name : Dictionaries
    uri : /dictionaries
    page : dictionaries
    fa-icon : book
  - name : Languages
    uri : /languages
    page : languages
    fa-icon : language
  - name : Translations
    uri : /translations
    page : translations
    fa-icon : comment